### ISSUE TITLE
TypeError: Cannot read property 'deviceGuid' of undefined

### ISSUE THREAD

**Issue by lockpicker** [codyc1515/homebridge-panasonic-air-conditioner#14]
Hi, 
Trying to use the plugin with the below config - 
"accessories": [{
		"accessory": "PanasonicAirConditioner",
		"name": "Bedroom AC",
		"email": "<email_here>",
		"password": "<plain_text_password_here>",
		"Debug logging": true
	}]

results in the following error and crash:
at PanasonicAC.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/index.js:77:60)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:197:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:285:13)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

Also, perhaps you could include a sample config.json in the repo.

**Comment by lockpicker** [comment]
Nevermind. The accessory wasn't shared with the account I was using. 
However worth capturing this and logging an appropriate note in the logs.
