### ISSUE TITLE
Unable to post get command to API

### ISSUE THREAD

**Issue by DrDirtyDevil** [codyc1515/homebridge-panasonic-air-conditioner#17]
`[1/24/2020, 9:31:44 PM] [Coffee Maker] Could not send GET command | Unknown error. Did the API version change? TypeError: Cannot read property 'statusCode' of undefined
    at PanasonicAC.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/index.js:230:76)
    at self.callback (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
`

**Comment by EvertJob** [comment]
What app version are you using?

**Comment by codyc1515** [comment]
Closing due no response
