### ISSUE TITLE
Support for multiple AC Units

### ISSUE THREAD

**Issue by stevenmarq** [codyc1515/homebridge-panasonic-air-conditioner#28]
Hi there,
Great plugin! Do you have any plans to add support for multiple AC units? Alternatively, is there a workaround that I can use to add more than one AC?

**Comment by codyc1515** [comment]
It's under "Advanced configuration" if you are using the config-ui-x web UI. Otherwise, just specify in your config, for instance:

`"devicenumber": 2`

**Comment by stevenmarq** [comment]
Thank you for the quick response! Unfortunately, that does not seem to work. I'm getting the following error when using the "devicenumber" attribute.

`[6/6/2020, 7:47:09 AM] [Panasonic AC 1] Could not find any devices. Error # undefined undefined
HAP Warning: Characteristic 00000077-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BC-0000-1000-8000-0026BB765291. Adding anyway.
[6/6/2020, 7:47:10 AM] [Panasonic AC 2] Login complete
[6/6/2020, 7:47:10 AM] [Panasonic AC 2] Could not find device by number. Check your device number and try again. TypeError: Cannot read property 'deviceIdList' of undefined
    at PanasonicAC.<anonymous> (/homebridge/node_modules/homebridge-panasonic-air-conditioner/index.js:159:60)
    at Request.self.callback (/homebridge/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/homebridge/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) Error # undefined undefined
HAP Warning: Characteristic 00000077-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BC-0000-1000-8000-0026BB765291. Adding anyway.
[6/6/2020, 7:47:10 AM] [Panasonic AC 2] Refresh start
[6/6/2020, 7:47:12 AM] [Panasonic AC 2] Refresh failed. HTTP response 403 Error # undefined undefined`
