### ISSUE TITLE
"devicenumber" attribute not working

### ISSUE THREAD

**Issue by stevenmarq** [codyc1515/homebridge-panasonic-air-conditioner#29]
Using the "devicenumber" attribute throws the following error:

`[6/6/2020, 7:47:09 AM] [Panasonic AC 1] Could not find any devices. Error # undefined undefined HAP Warning: Characteristic 00000077-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BC-0000-1000-8000-0026BB765291. Adding anyway. [6/6/2020, 7:47:10 AM] [Panasonic AC 2] Login complete [6/6/2020, 7:47:10 AM] [Panasonic AC 2] Could not find device by number. Check your device number and try again. TypeError: Cannot read property 'deviceIdList' of undefined at PanasonicAC.<anonymous> (/homebridge/node_modules/homebridge-panasonic-air-conditioner/index.js:159:60) at Request.self.callback (/homebridge/node_modules/request/request.js:185:22) at Request.emit (events.js:315:20) at Request.<anonymous> (/homebridge/node_modules/request/request.js:1154:10) at Request.emit (events.js:315:20) at IncomingMessage.<anonymous> (/homebridge/node_modules/request/request.js:1076:12) at Object.onceWrapper (events.js:421:28) at IncomingMessage.emit (events.js:327:22) at endReadableNT (_stream_readable.js:1221:12) at processTicksAndRejections (internal/process/task_queues.js:84:21) Error # undefined undefined HAP Warning: Characteristic 00000077-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BC-0000-1000-8000-0026BB765291. Adding anyway. [6/6/2020, 7:47:10 AM] [Panasonic AC 2] Refresh start [6/6/2020, 7:47:12 AM] [Panasonic AC 2] Refresh failed. HTTP response 403 Error # undefined undefined`

**Comment by codyc1515** [comment]
403 Error indicates that the username or password is incorrect. Can you please check this and try again?

**Comment by codyc1515** [comment]
Improved error handling added in https://github.com/codyc1515/homebridge-panasonic-air-conditioner/commit/35ec0240d399a380bf43cb46c7352bf99c4d6e91

**Comment by stevenmarq** [comment]
Unfortunately, that's not the problem. User name and password are correct. If I remove the devicenumber attribute from the configuration, it works with the very same credentials. 
This is the error message that I get in the new version of the plugin:

`[8/10/2020, 1:46:02 PM] Homebridge is running on port 52275.
[8/10/2020, 1:46:07 PM] [AC1] Login complete
[8/10/2020, 1:46:07 PM] [AC1] Could not find device by number. Check your device number and try again. TypeError: Cannot read property 'deviceIdList' of undefined
    at PanasonicAC.<anonymous> (/homebridge/node_modules/homebridge-panasonic-air-conditioner/index.js:159:60)
    at Request.self.callback (/homebridge/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/homebridge/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) Error # undefined undefined
HAP Warning: Characteristic 00000077-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BC-0000-1000-8000-0026BB765291. Adding anyway.
[8/10/2020, 1:46:07 PM] [AC1] Refresh start
[8/10/2020, 1:46:08 PM] [AC1] Refresh failed. Authorization error. Did you enter the correct username and password? Please check the details & restart Homebridge. null
[8/10/2020, 1:46:44 PM] [AC1] SET Active 0 start
[8/10/2020, 1:46:45 PM] [AC1] SET failed. HTTP response 400 Error # 4002 Missing required body parameter`
