### ISSUE TITLE
Login Faild error #4106

### ISSUE THREAD

**Issue by yakemishan** [codyc1515/homebridge-panasonic-air-conditioner#44]
Hey,

Since update I get an error #4106. It says: New version of app has been published.

I use the latest one.

**Comment by ursusHU** [comment]
this refers to the panasonic comfort cloud app. 
https://github.com/codyc1515/homebridge-panasonic-air-conditioner/issues/36#issuecomment-688649980

**Comment by miguelsasso** [comment]
I updated the version number in index.js, but it appears Panasonic have changed something in the API.  Can anyone confirm?

23/12/2020, 13:02:58 [Airc Con 1] Could not find device by number. Check your device number and try again. TypeError: Cannot read property '0' of undefined
    at PanasonicAC.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-panasonic-air-conditioner/index.js:167:75)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) Error # undefined undefined

**Comment by xDiavelS** [comment]
I’m getting the same error after changing the app version in the index.js file.

**Comment by rupertbg** [comment]
The fix is working on mine, should we push it to npm?

**Comment by yakemishan** [comment]
Yes please

**Comment by veztr** [comment]
Please push the newest version to NPM so that I'm that I have the right files. Thanks.

**Comment by codyc1515** [comment]
This should be resolved now. Apologies for the delay. We have a long holiday here and I didn't have my computer with me.
