### ISSUE TITLE
Refresh failed. Token error. The token may have expired. null

### ISSUE THREAD

**Issue by tbraas** [codyc1515/homebridge-panasonic-air-conditioner#46]
Ever since at least Dec 30th, version 4.1.1 of this fine plugin no longer works. I'm getting a couple different errors that I suspect are due to the same root cause.

The most common error is:
[01/01/2021, 15:30:53] [Panasonic Air Conditioner] Refresh failed. Token error. The token may have expired. null

I also get ([discussed in issue #44 ](https://github.com/codyc1515/homebridge-panasonic-air-conditioner/issues/44), I am running the latest version of the app and ensured that the homebridge user has the requisite access.
[01/01/2021, 15:10:56] [Panasonic Air Conditioner] Login failed. Error # 4106 New version app has been published

And finally:
[01/01/2021, 07:51:00] [Panasonic Air Conditioner] Login failed. Unknown error. Did the API version change? TypeError: Cannot read property 'code' of undefined
    at PanasonicAC.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/index.js:178:51)
    at self.callback (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by codyc1515** [comment]
This should be fixed now. Apologies for the delay. We have a long holiday here and I didn't have my computer with me.

**Comment by tbraas** [comment]
Thanks mate!
