### ISSUE TITLE
typerror with version 5.0 ?

### ISSUE THREAD

**Issue by JurgenLB** [codyc1515/homebridge-panasonic-air-conditioner#51]
Do someone also have this issue?
Is there a change in the Json or the API ?

Initializing PanasonicAirConditioner accessory...
TypeError: Cannot read property 'NOTIFY' of undefined
at PanasonicAC.getServices (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/index.js:141:19)
at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:427:36)
at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:309:26)
at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:959:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
at Module.load (internal/modules/cjs/loader.js:815:32)
at Function.Module._load (internal/modules/cjs/loader.js:727:14)
Got SIGTERM, shutting down Homebridge...
[2021-1-17 19:56:39] TypeError: Cannot read property 'addEntry' of undefined
at PanasonicAC.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/index.js:254:27)
at Request.self.callback (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:185:22)
at Request.emit (events.js:210:5)
at Request.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:1154:10)
at Request.emit (events.js:210:5)
at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:1076:12)
at Object.onceWrapper (events.js:299:28)
at IncomingMessage.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1184:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
homebridge.service: Main process exited, code=exited, status=143/n/a
homebridge.service: Failed with result 'exit-code'.

**Comment by codyc1515** [comment]
Do you want to check again with the latest version?

**Comment by JurgenLB** [comment]
yes this seams to work. Thanks

only when installing I have some errors.
request@2.88.2: request has been deprecated
har-validator@5.1.5: this library is no longer supported

is there a solution for or can we help with this?
