### ISSUE TITLE
'Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined)

### ISSUE THREAD

**Issue by akirakev** [codyc1515/homebridge-panasonic-air-conditioner#65]
Getting an undefined value error when running the plugin 

[4/27/2021, 10:07:30 PM] [homebridge-panasonic-air-conditioner] This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[4/27/2021, 10:07:30 PM] [homebridge-panasonic-air-conditioner] Error: 
    at TargetHeaterCoolerState.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at TargetHeaterCoolerState.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at TargetHeaterCoolerState.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at PanasonicAC.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/index.js:296:82)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:185:22)
    at Request.emit (node:events:376:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:376:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:482:28)

**Comment by akirakev** [comment]
i think it might be that the plugin is missing the DRY state, Auto, Heat, Cool and Dry

**Comment by tampiss** [comment]
I have the same:

[29/04/2021, 08:13:25] [AirCon] Temperature state is not available 126 126
[29/04/2021, 08:13:25] [homebridge-panasonic-air-conditioner] This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

As I think my AirCon does not report the temp back at all.

M

**Comment by xyz667** [comment]
Same Issue here:
"This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info." every 60 seconds (x 2 because I have two aircons)

**Comment by efipso** [comment]
I have the same two errors every minute:

[3/6/2021 9:22:15] [Panasonic AC] Temperature state is not available 126 126
[3/6/2021 9:22:15] [homebridge-panasonic-air-conditioner] This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

I repeat, every minute. 

It's possible to show those errors only in debug mode, please?

**Comment by putthegundownkinkade** [comment]
Same issue here


[01/07/2021, 08:40:28] [homebridge-panasonic-air-conditioner] This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

**Comment by CharlesMonneron** [comment]
Same issue as above. It seems that the temperature state is not updated if the unit is not active. This is not a plugin problem as one has the same issue in the native iOS app. Also the « OFF » state seems to not be recognised by homebridge and create the « undefined » error message, I force it to « COOL » as I live in hot climate anyway…

I did a quick and dirty edit of index.js at lines 244 and 300 to avoid the messages, but I admit this is not ideal …

> in 244
> >                              else {this.log("Temperature state is not available", body.parameters.insideTemperature, body.parameters.outTemperature);}
> replaced by 
> >                               // Note - update of fake temperature to avoid error messages polluting the log
> >                               else {
> >                                       this.HeaterCooler.getCharacteristic(Characteristic.CurrentTemperature).updateValue(30);
> >                                       this.FakeGatoHistory.addEntry({time: moment().unix(), temp: this.temperature});
> >                               }
> in 300
> >                                       this.HeaterCooler.getCharacteristic(Characteristic.TargetHeaterCoolerState).updateValue(Characteristic.TargetHeaterCoolerState.OFF);
> replaced by
> >                                       this.HeaterCooler.getCharacteristic(Characteristic.TargetHeaterCoolerState).updateValue(Characteristic.TargetHeaterCoolerState.COOL);
>

**Comment by JurgenLB** [comment]
same issue here


Starting to advertise 'Homebridge CBBF' using bonjour-hap backend!
[2021-7-28 22:26:27] Homebridge v1.3.4 (Homebridge) is running on port 51826.
[2021-7-28 22:26:31] [homebridge-panasonic-air-conditioner] This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[2021-7-28 22:26:31] [homebridge-panasonic-air-conditioner] Error: 
    at TargetHeaterCoolerState.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at TargetHeaterCoolerState.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at TargetHeaterCoolerState.Characteristic.updateValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at PanasonicAC.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/index.js:300:82)
    at Request.self.callback (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
[2021-7-28 22:26:31] [homebridge-panasonic-air-conditioner] This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[2021-7-28 22:26:31] [homebridge-panasonic-air-conditioner] Error: 
    at TargetHeaterCoolerState.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at TargetHeaterCoolerState.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at TargetHeaterCoolerState.Characteristic.updateValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at PanasonicAC.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/index.js:300:82)
    at Request.self.callback (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
[2021-7-28 22:26:31] [homebridge-panasonic-air-conditioner] This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[2021-7-28 22:26:31] [homebridge-panasonic-air-conditioner] Error: 
    at TargetHeaterCoolerState.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at TargetHeaterCoolerState.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at TargetHeaterCoolerState.Characteristic.updateValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at PanasonicAC.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/index.js:300:82)
    at Request.self.callback (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)

**Comment by veitch123** [comment]
> I have the same two errors every minute:
> 
> [3/6/2021 9:22:15] [Panasonic AC] Temperature state is not available 126 126
> [3/6/2021 9:22:15] [homebridge-panasonic-air-conditioner] This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
> 
> I repeat, every minute.
> 
> It's possible to show those errors only in debug mode, please?

Yeah I'm getting them too. It's a pain because it means I have to scroll up for anything meaningful. 

Anyway thanks for this amazing plugin. I only wish the characteristic value was a valid finite number whatever that means.

**Comment by veitch123** [comment]
A number, a number, my kingdom for a valid finite number.

**Comment by codyc1515** [comment]
Fixed.
