### ISSUE TITLE
'Cooling Threshold Temperature' characteristic  error 

### ISSUE THREAD

**Issue by akirakev** [codyc1515/homebridge-panasonic-air-conditioner#80]
[homebridge-panasonic-air-conditioner] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 10 exceeded minimum of 16. See https://git.io/JtMGR for more info.
[1/24/2022, 3:10:45 PM] [homebridge-panasonic-air-conditioner] Error: 
    at CoolingThresholdTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at CoolingThresholdTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2045:14)
    at CoolingThresholdTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1582:21)
    
    Let me know if you need a full trace/

**Comment by 1homebridge** [comment]
I am also having this issue. Has yours not been resolved since January?

**Comment by codyc1515** [comment]
This plug-in is now archived and it is advised to use the [homebridge-panasonic-ac-platform](https://github.com/embee8/homebridge-panasonic-ac-platform) plug-in instead. It is based on this plug-in. This plug-in provides support for the devices as a platform (instead of just individual accessories).
